aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK11/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK11/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK1/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK1/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K10/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K10/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK19_BCC2/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK19_BCC2/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK4_P/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK4_P/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K19/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K19/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K9/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K9/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K12/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K12/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K15/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K15/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK16/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK16/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K26/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K26/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK5/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK5/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K22/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K22/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K16/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K16/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK20/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK20/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK8/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK8/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK7/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK7/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K13/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K13/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK14/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK14/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK21/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK21/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K17/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K17/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K23/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K23/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K6/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K6/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK2/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK2/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K2/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K2/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K20/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K20/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K7/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K7/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K21/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K21/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK17_M/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK17_M/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK13/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK13/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/Ck22/exhibit.json s3://www.cycif.org/110-Komen_BRCA/Ck22/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K27/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K27/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K24/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K24/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK3_R/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK3_R/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K14/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K14/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K8/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K8/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K1/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K1/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK24/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK24/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK6/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK6/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K4/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K4/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK18_P/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK18_P/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK9/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK9/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K18/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K18/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K5/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K5/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK10/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK10/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK12/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK12/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK23/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK23/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/Ck19_BCC/exhibit.json s3://www.cycif.org/110-Komen_BRCA/Ck19_BCC/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK15/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK15/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K3/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K3/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK4_R/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK4_R/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/CK25_R/exhibit.json s3://www.cycif.org/110-Komen_BRCA/CK25_R/exhibit.json
aws s3 cp --acl public-read /Users/jth30/projects/komen/outputs/K11/exhibit.json s3://www.cycif.org/110-Komen_BRCA/K11/exhibit.json
